### ISSUE TITLE
Python 3 Incompatibility

### ISSUE THREAD

**Issue by derks** [datafolklabs/boss#22]
* Boss Version: `master`
 * Python Version: 3.4.2

```
$ boss create ./tmp/myapp -t boss:cement-app
Traceback (most recent call last):
  File "/Users/derks/.env/boss-py3/bin/boss", line 9, in <module>
    load_entry_point('boss==0.9.17.dev20141206033655', 'console_scripts', 'boss')()
  File "/Users/derks/Development/boss/boss/cli/main.py", line 54, in main
    app.run()
  File "/Users/derks/.env/boss-py3/lib/python3.4/site-packages/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/Users/derks/.env/boss-py3/lib/python3.4/site-packages/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/Users/derks/Development/boss/boss/cli/controllers/base.py", line 73, in create
    src.create_from_template(source, template, self.app.pargs.extra[0])
  File "/Users/derks/Development/boss/boss/cli/source.py", line 63, in create_from_template
    tmpl.copy(dest_dir)
  File "/Users/derks/Development/boss/boss/cli/template.py", line 252, in copy
    self._populate_vars()
  File "/Users/derks/Development/boss/boss/cli/template.py", line 94, in _populate_vars
    res = raw_input("%s: [%s] " % (question, default))
NameError: name 'raw_input' is not defined
```

**Comment by fxstein** [comment]
Very much appreciated!
